### ISSUE TITLE
Cluster looks like ready to import when it's importing already

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/ui#585] opened 2017-09-11 08:25 UTC
For cluster, which is importing, should not be possible to run another import task.

Steps to reproduce:
1. Start to import cluster via UI
2. Go to 'Clusters' page

Current behavior:
The cluster seems to be ready to import. It is possible to click on `Import Cluster` button

Expected behavior:
The cluster should not look like it could be imported, `Import Cluster` button should not be available.

![import_cluster_button](https://user-images.githubusercontent.com/22369834/30265113-6bb5aaec-96db-11e7-9836-1d317905dd27.png)

Used packages:
tendrl-node-agent-1.5.1-1.el7.centos.noarch
tendrl-monitoring-integration-1.5.1-1.el7.centos.noarch
tendrl-commons-1.5.1-1.el7.centos.noarch
tendrl-api-1.5.1-1.el7.centos.noarch
tendrl-api-httpd-1.5.1-1.el7.centos.noarch
tendrl-ui-1.5.1-1.el7.centos.noarch

**Comment by gnehapk** [comment] 2017-09-11 09:08
Duplicate of #531

**Closed as completed** 2017-09-11 11:23 UTC
