### ISSUE TITLE
UI shows value as disabled if "profiling_enabled is coming as empty string

### ISSUE THREAD

**Issue by cloudbehl** [Tendrl/ui#953] opened 2018-04-26 06:19 UTC
![image](https://user-images.githubusercontent.com/6695156/39288985-d8691678-4947-11e8-93c3-cb2647789771.png)

**Comment by gnehapk** [comment] 2018-05-18 05:12
Duplicate of #959. Hence,closing it.

**Closed as completed by gnehapk** 2018-05-18 05:12 UTC
