### ISSUE TITLE
[RFE] Cluster name / unique identifier is unwieldy

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#582] opened 2017-09-08 19:58 UTC
The clusters that get imported have very long unique identifiers that get truncated in the UI, e.g. in the context switcher and all places where the cluster name is displayed.

Is it possible to come up with a more user-friendly unique identifier that gets auto-created or auto-assigned?  E.g. YYMMDDHHMM (and maybe leave of the prefix "Gluster-" which takes up 8 letters).  To address leaving of the "Gluster-" prefix, let's add it to the Cluster Version, e.g. GlusterFS 3.12.0.

<img width="1280" alt="screen shot 2017-09-08 at 3 08 50 pm" src="https://user-images.githubusercontent.com/5589919/30228831-6e21363c-94ad-11e7-825c-03b7782f89ef.png">

<img width="1280" alt="screen shot 2017-09-08 at 3 08 32 pm" src="https://user-images.githubusercontent.com/5589919/30228844-7a7a26fa-94ad-11e7-892a-73c3fc31eb64.png">

@Tendrl/tendrl-core @Tendrl/qe @mcarrano @japplewhite

**Comment by julienlim** [comment] 2018-03-29 18:02
There is a proposal to solve this at Tendrl/commons#888.

**Comment by gnehapk** [comment] 2018-09-11 00:30
Closing this issue as fixed already.

**Closed as completed by gnehapk** 2018-09-11 00:30 UTC

**Comment by sankarshanmukhopadhyay** [comment] 2018-09-11 00:34
Does the workflow not require that this issue be cited in the PR which fixes it so that there is a link to the PR on the issue itself?

**Comment by gnehapk** [comment] 2018-09-11 00:56
@sankarshanmukhopadhyay this issue is a duplicate of https://github.com/Tendrl/ui/issues/656 where all the PRs have been tracked and attached. 

The PR for this change is - https://github.com/Tendrl/ui/pull/925
